services:
  backend-api:
    image: ghcr.io/santimakci/dssd-api-cloud:main
    restart: always
    command: npm run start:debug
    container_name: backend-api
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/usr/src/app
    networks:
      - main
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: backend-db
    restart: unless-stopped
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  postgres_data:
